### ISSUE TITLE
Practica7

### ISSUE THREAD

**Issue by YulianaMorales18** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-YulianaMorales18#1]
[practica1_Yuli (4).pdf](https://github.com/user-attachments/files/17469369/practica1_Yuli.4.pdf)

**Comment by mae18-25** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:23/25
Total:98/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
